<h1> Reinforcement Learning Trading </h1>

<h2>Key Components: </h2>
<ul>
    <li><strong>Agent:</strong>The trading algorithm that interacts with the environment.</li>
    <li><strong>Environment:</strong>The market (historical price data or real-time trading platform</li>
    <li><strong>Actions:</strong>The decisions the agent can make, such as buying, selling, or holding an asset.</li>
    <li><strong>Rewards:</strong>The feedback the agent receives based on its actions, such as profits (positive reward) or losses (negative reward)</li>
    <li><strong>Policy:</strong>The strategy the agent uses to decide which action to take at each step.</li>
</ul>

<h2>Advancements in Trading</h2>
<ul>
    <li><strong>Adaptability: </strong>The RL agent can adapt to market changes and learn from patterns in historical or real-time data.</li>
    <li><strong>Automation: </strong>RL automates decision-making, allowing it to handle complex and high-frequency trading strategies.</li>
    <li><strong>Optimization: </strong>It can optimize for long-term returns and other performance metrics like the Sharpe ratio or risk-adjusted returns.</li>
</ul>

In [3]:
import yfinance as yf
from datetime import datetime, timedelta

# Calculate 15 years ago from today
today = datetime.now()
fifteen_years_ago = today - timedelta(days=15*365.25)  # Account for leap years
yesterday = datetime.now() - timedelta(days=1)

data = yf.download('^GSPC', start=fifteen_years_ago, end=yesterday)

data.head()

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2009-09-30,1061.020020,1063.400024,1046.469971,1057.079956,1057.079956,5998860000
2009-10-01,1054.910034,1054.910034,1029.449951,1029.849976,1029.849976,5791450000
2009-10-02,1029.709961,1030.599976,1019.950012,1025.209961,1025.209961,5583240000
2009-10-05,1026.869995,1042.579956,1025.920044,1040.459961,1040.459961,4313310000
2009-10-06,1042.020020,1060.550049,1042.020020,1054.719971,1054.719971,5029840000

In [5]:
data.index

DatetimeIndex(['2009-09-30', '2009-10-01', '2009-10-02', '2009-10-05',
               '2009-10-06', '2009-10-07', '2009-10-08', '2009-10-09',
               '2009-10-12', '2009-10-13',
               ...
               '2024-09-16', '2024-09-17', '2024-09-18', '2024-09-19',
               '2024-09-20', '2024-09-23', '2024-09-24', '2024-09-25',
               '2024-09-26', '2024-09-27'],
              dtype='datetime64[ns]', name='Date', length=3774, freq=None)

<h2>Forward Fill Missing Values (weekends & holidays)</h2>

In [9]:
import pandas as pd
data.index = pd.to_datetime(data.index)
data.index

DatetimeIndex(['2009-09-30', '2009-10-01', '2009-10-02', '2009-10-05',
               '2009-10-06', '2009-10-07', '2009-10-08', '2009-10-09',
               '2009-10-12', '2009-10-13',
               ...
               '2024-09-16', '2024-09-17', '2024-09-18', '2024-09-19',
               '2024-09-20', '2024-09-23', '2024-09-24', '2024-09-25',
               '2024-09-26', '2024-09-27'],
              dtype='datetime64[ns]', name='Date', length=3774, freq=None)

In [10]:
date_range = pd.date_range(start=data.index.min(), end=data.index.max())
missing_dates = date_range.difference(data.index)
print(f"Missing Dates: {missing_dates}")

Missing Dates: DatetimeIndex(['2009-10-03', '2009-10-04', '2009-10-10', '2009-10-11',
               '2009-10-17', '2009-10-18', '2009-10-24', '2009-10-25',
               '2009-10-31', '2009-11-01',
               ...
               '2024-08-25', '2024-08-31', '2024-09-01', '2024-09-02',
               '2024-09-07', '2024-09-08', '2024-09-14', '2024-09-15',
               '2024-09-21', '2024-09-22'],
              dtype='datetime64[ns]', length=1703, freq=None)

In [11]:
# Reindex the DataFrame to include all the dates
data_full = data.reindex(date_range)

# Fill missing values with forward fill (propogating the last known value)
data_full.fillna(method='ffill', inplace=True)

missing_values = data_full.isnull().sum()
print(f"Missing values after forward fill: \n{missing_values}")

Missing values after forward fill:
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [12]:
date_range = pd.date_range(start=data_full.index.min(), end=data_full.index.max())
missing_dates = date_range.difference(data_full.index)
print(f"Missing Dates: {missing_dates}")

Missing Dates: DatetimeIndex([], dtype='datetime64[ns]', freq='D')

In [14]:
data_full.head(30)

,Open,High,Low,Close,Adj Close,Volume
2009-09-30,1061.020020,1063.400024,1046.469971,1057.079956,1057.079956,5.998860e+09
2009-10-01,1054.910034,1054.910034,1029.449951,1029.849976,1029.849976,5.791450e+09
2009-10-02,1029.709961,1030.599976,1019.950012,1025.209961,1025.209961,5.583240e+09
2009-10-03,1029.709961,1030.599976,1019.950012,1025.209961,1025.209961,5.583240e+09
2009-10-04,1029.709961,1030.599976,1019.950012,1025.209961,1025.209961,5.583240e+09
2009-10-05,1026.869995,1042.579956,1025.920044,1040.459961,1040.459961,4.313310e+09
2009-10-06,1042.020020,1060.550049,1042.020020,1054.719971,1054.719971,5.029840e+09
2009-10-07,1053.650024,1058.020020,1050.099976,1057.579956,1057.579956,4.238220e+09
2009-10-08,1060.030029,1070.670044,1060.030029,1065.479980,1065.479980,4.988400e+09
2009-10-09,1065.280029,1071.510010,1063.000000,1071.489990,1071.489990,3.763780e+09
2009-10-10,1065.280029,1071.510010,1063.000000,1071.489990,1071.489990,3.763780e+09
2009-10-11,1065.280029,1071.510010,1063.000000,1071.489990,1071.489990,3.763780e+09
2009-10-12,1071.630005,1079.459961,1071.630005,1076.189941,1076.189941,3.710430e+09
2009-10-13,1074.959961,1075.300049,1066.709961,1073.189941,1073.189941,4.320480e+09
2009-10-14,1078.680054,1093.170044,1078.680054,1092.020020,1092.020020,5.406420e+09
2009-10-15,1090.359985,1096.560059,1086.410034,1096.560059,1096.560059,5.369780e+09
2009-10-16,1094.670044,1094.670044,1081.530029,1087.680054,1087.680054,4.894740e+09
2009-10-17,1094.670044,1094.670044,1081.530029,1087.680054,1087.680054,4.894740e+09
2009-10-18,1094.670044,1094.670044,1081.530029,1087.680054,1087.680054,4.894740e+09
2009-10-19,1088.219971,1100.170044,1086.479980,1097.910034,1097.910034,4.619240e+09
2009-10-20,1098.640015,1098.640015,1086.160034,1091.060059,1091.060059,5.396930e+09
2009-10-21,1090.359985,1101.359985,1080.770020,1081.400024,1081.400024,5.616290e+09
2009-10-22,1080.959961,1095.209961,1074.310059,1092.910034,1092.910034,5.192410e+09
2009-10-23,1095.619995,1095.829956,1075.489990,1079.599976,1079.599976,4.767460e+09
2009-10-24,1095.619995,1095.829956,1075.489990,1079.599976,1079.599976,4.767460e+09
2009-10-25,1095.619995,1095.829956,1075.489990,1079.599976,1079.599976,4.767460e+09
2009-10-26,1080.359985,1091.750000,1065.229980,1066.949951,1066.949951,6.363380e+09
2009-10-27,1067.540039,1072.479980,1060.619995,1063.410034,1063.410034,5.337380e+09
2009-10-28,1061.510010,1063.260010,1042.189941,1042.630005,1042.630005,6.600350e+09
2009-10-29,1043.689941,1066.829956,1043.689941,1066.109985,1066.109985,5.595040e+09

<h2>Pre-process data</h2>
<ul>
    <li>Normalize</li>
    <li>Extract relevant features (Close and Volume) No additional Bias</li>
</ul>

In [16]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
data_scaled = scaler.fit_transform(data_full[['Close', 'Volume']])

<h2>Interact with the Environment</h2>

In [18]:
import gym
from gym import spaces
import numpy as np

class TradingEnv(gym.Env):
    def __init__(self, data):
        self.data = data
        self.current_step = 0
        self.action_space = spaces.Discrete(3)  # Buy, Hold, Sell
        self.observation_space = spaces.Box(low=-np.inf, high=np.inf, shape=(data.shape[1],))
        
    def reset(self):
        self.current_step = 0
        return self.data[self.current_step]

    def step(self, action):
        reward = 0
        done = False
        # Define action logic here
        self.current_step += 1
        return self.data[self.current_step], reward, done, {}

ModuleNotFoundError: No module named 'gym'